export const TEST_LOAD = "TEST_LOAD";
export const TEST_NEW = "TEST_NEW";

export const EDITOR_SAVE_STATE = "EDITOR_SAVE_STATE";

export const MODEL_ADD = "MODEL_ADD";
export const MODEL_CLOSE = "MODEL_CLOSE";
export const MODEL_CLOSE_ALL = "MODEL_CLOSE_ALL";
export const MODEL_SELECT = "MODEL_SELECT";
export const MODEL_UPDATE = "MODEL_UPDATE";

export const ELEMENT_CREATE = "ELEMENT_CREATE";
export const ELEMENT_DELETE = "ELEMENT_DELETE";
export const ELEMENT_SELECT = "ELEMENT_SELECT";
export const ELEMENT_START = "ELEMENT_START";
export const ELEMENT_UPDATE = "ELEMENT_UPDATE";
export const ELEMENT_UPDATE_POSITION = "ELEMENT_UPDATE_POSITION";

export const EXECUTION_BREAKPOINT_TOGGLE = "EXECUTION_BREAKPOINT_TOGGLE";
export const EXECUTION_CONNECT = "EXECUTION_CONNECT";
export const EXECUTION_DELAY = "EXECUTION_DELAY";
export const EXECUTION_FAILED = "EXECUTION_FAILED";
export const EXECUTION_FULFILLED = "EXECUTION_FULFILLED";
export const EXECUTION_LOAD = "EXECUTION_LOAD";
export const EXECUTION_PAUSE = "EXECUTION_PAUSE";
export const EXECUTION_RUN = "EXECUTION_RUN";
export const EXECUTION_STEP = "EXECUTION_STEP";
export const EXECUTION_STOP = "EXECUTION_STOP";

export const EDITOR_PROPERTIES_TOGGLE = "EDITOR_PROPERTIES_TOGGLE";
