name: Build and test on latest Windows and Java 17

on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Grant execute permission for mvnw
      run: chmod +x mvnw
    - name: Build with Maven
      run: ./mvnw -B package --file pom.xml

